CREATE TABLE [User] (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    PhoneNo VARCHAR(8) NOT NULL,
    UserName NVARCHAR(50) NOT NULL DEFAULT '',
    Passcode VARCHAR(255) NOT NULL DEFAULT '',
    RoleType NVARCHAR(50) NOT NULL DEFAULT '',
    DateTimeCreated DATETIMEOFFSET DEFAULT GETDATE(),
    DateTimeUpdated DATETIMEOFFSET DEFAULT GETDATE(),
    CONSTRAINT PK_User PRIMARY KEY (Id, PhoneNo)
);
