CREATE TABLE [User] (
  Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  PhoneNo VARCHAR(8) NOT NULL,
  UserName NVARCHAR(50) NOT NULL DEFAULT '',
  Passcode VARCHAR(255) NOT NULL DEFAULT '',
  RoleType NVARCHAR(50) NOT NULL DEFAULT '',
  DateTimeCreated DATETIMEOFFSET DEFAULT GETDATE(),
  DateTimeUpdated DATETIMEOFFSET DEFAULT GETDATE(),
  CONSTRAINT PK_User PRIMARY KEY (Id)
);

CREATE TABLE [Order] (
  Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  OrderName VARCHAR(100) NOT NULL,
  OrderDescription VARCHAR(5000) NULL,
  OrderDate DATETIMEOFFSET DEFAULT GETDATE(),
  UserId UNIQUEIDENTIFIER NOT NULL,
  FoodName NVARCHAR(100) NOT NULL,
  FoodCustomization NVARCHAR(100) NOT NULL,
  FoodPrice DECIMAL(11, 2) NOT NULL,
  Quantity DECIMAL(11, 2) NOT NULL,
  CONSTRAINT PK_Order PRIMARY KEY CLUSTERED (Id ASC),
  CONSTRAINT FK_User_Order FOREIGN KEY (UserId) REFERENCES [User] (Id)
);

CREATE TABLE [Stall] (
  Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  StallName VARCHAR(100) NOT NULL,
  StallDescription VARCHAR(5000) NULL,
  StallOwner VARCHAR(100) NOT NULL,
  DateTimeCreated DATETIMEOFFSET DEFAULT GETDATE(),
  DateTimeUpdated DATETIMEOFFSET DEFAULT GETDATE(),
  CONSTRAINT PK_Stall PRIMARY KEY CLUSTERED (Id ASC)
);

CREATE TABLE [Payment] (
  Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  OrderID UNIQUEIDENTIFIER NOT NULL,
  Amount DECIMAL(19, 4) NOT NULL,
  StallID UNIQUEIDENTIFIER NOT NULL,
  PaymentStatus VARCHAR(10) NOT NULL,
  DateTimeCreated DATETIMEOFFSET DEFAULT GETDATE(),
  DateTimeUpdated DATETIMEOFFSET DEFAULT GETDATE(),
  CONSTRAINT PK_Payment PRIMARY KEY CLUSTERED (Id ASC),
  CONSTRAINT FK_Payment_Stall FOREIGN KEY (StallID) REFERENCES [Stall] (Id),
  CONSTRAINT FK_Payment_Order FOREIGN KEY (OrderID) REFERENCES [Order] (Id)
);

CREATE TABLE [CustomerEnquiries] (
  Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  EnquiriesSubject VARCHAR(1000) NOT NULL,
  EnquiriesDescription VARCHAR(5000) NOT NULL,
  DateTimeCreated DATETIMEOFFSET DEFAULT GETDATE(),
  DateTimeUpdated DATETIMEOFFSET DEFAULT GETDATE(),
  IsDeleted BIT NULL,
  UserId UNIQUEIDENTIFIER NOT NULL,
  CONSTRAINT PK_CustomerEnquiries PRIMARY KEY CLUSTERED (Id ASC),
  CONSTRAINT FK_Customer_CustomerEnquiries FOREIGN KEY (UserId) REFERENCES [User] (Id)
);

CREATE TABLE [Foods] (
  Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  FoodName VARCHAR(100) NOT NULL,
  FoodDescription VARCHAR(5000) NULL,
  FoodPrice DECIMAL(11, 2) NOT NULL,
  DateTimeCreated DATETIMEOFFSET DEFAULT GETDATE(),
  DateTimeUpdated DATETIMEOFFSET DEFAULT GETDATE(),
  IsDeleted BIT NULL,
  StallId UNIQUEIDENTIFIER NOT NULL,
  CONSTRAINT PK_Foods PRIMARY KEY CLUSTERED (Id ASC),
  CONSTRAINT FK_Food_Stall FOREIGN KEY (StallID) REFERENCES [Stall] (Id)
);

CREATE TABLE [FoodsCustomization] (
  Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  FoodCustomizationName VARCHAR(100) NOT NULL,
  FoodCustomizationPrice DECIMAL(11, 2) NOT NULL,
  DateTimeCreated DATETIMEOFFSET DEFAULT GETDATE(),
  DateTimeUpdated DATETIMEOFFSET DEFAULT GETDATE(),
  IsDeleted BIT NULL,
  FoodId UNIQUEIDENTIFIER NOT NULL,
  CONSTRAINT PK_FoodsCustomization PRIMARY KEY CLUSTERED (Id ASC),
  CONSTRAINT FK_Foods_FoodsCustomization FOREIGN KEY (FoodId) REFERENCES [Foods] (Id)
);

CREATE TABLE [StallRating] (
  [Id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  [StallId] UNIQUEIDENTIFIER NOT NULL,
  [UserId] UNIQUEIDENTIFIER NOT NULL,
  [Rating] INT NOT NULL CHECK (Rating >= 1 AND Rating <= 5), -- Assuming a rating scale from 1 to 5
  [Review] NVARCHAR(1000) NULL,
  [DateTimeCreated] DATETIMEOFFSET DEFAULT GETDATE(),
  [DateTimeUpdated] DATETIMEOFFSET DEFAULT GETDATE(),
  CONSTRAINT [PK_StallRating] PRIMARY KEY CLUSTERED ([Id] ASC),
  CONSTRAINT [FK_StallRating_Stall] FOREIGN KEY ([StallId]) REFERENCES [Stall] ([Id]),
  CONSTRAINT [FK_StallRating_User] FOREIGN KEY ([UserId]) REFERENCES [User] ([Id])
);
